DROP table if exists users, items;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT generated by default as identity not null primary key,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS items (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available bool NOT NULL,
    user_id BIGINT not null ,
    CONSTRAINT fk_user_id FOREIGN KEY(user_id)
    REFERENCES users(id) ON DELETE CASCADE

    );