DROP table if exists users, items, bookings, requests, comments;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT generated by default as identity not null primary key,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS requests(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    description varchar(255) not null,
    requestor_id BIGINT not null,
    created TIMESTAMP NOT NULL,
    CONSTRAINT fk_requests_requestor_id FOREIGN KEY(requestor_id)
    REFERENCES users(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available bool NOT NULL,
    user_id BIGINT not null ,
    request_id BIGINT,
    CONSTRAINT items_user_id FOREIGN KEY(user_id)
    REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT items_request_id FOREIGN KEY(request_id)
    REFERENCES requests(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id BIGINT NOT NULL,
    user_id BIGINT not null,
    status varchar(16) not null,
    CONSTRAINT fk_bookings_item_id FOREIGN KEY(item_id)
    REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_user_id FOREIGN KEY(user_id)
    REFERENCES users(id) ON DELETE CASCADE
    );



CREATE TABLE IF NOT EXISTS comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY not null PRIMARY KEY,
    text varchar(255) not null,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT fk_comments_item_id FOREIGN KEY(item_id)
    REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_author_id FOREIGN KEY(author_id)
    REFERENCES users(id) ON DELETE CASCADE
);